spring:
    application:
      name: pwr-profile-service
    jackson:
      serialization:
        write_dates_as_timestamps: false
    datasource:
      username: ${DB_USER}
      password: ${DB_PASS}
      url: ${DB_URL}
      driver-class-name: ${DB_DRIVER_CLASS_NAME:org.mariadb.jdbc.Driver}
    jpa:
      hibernate:
        ddl-auto: ${DB_HIBERNATE_DDL_AUTO:none}
eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
server:
    port: 9004
logging:
  level:
    ROOT: info
    de.hbt.pwr: debug
    org.springframework.web: debug
  file: profile-service.log
# This service can be polite!
isPolite: true
default-chars-per-line: 32
feign:
  hystrix:
    enabled: true # Enables Hystrix Fallback for Feign clients.
---
spring:
  profiles: bootstrapDatabase
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: pwr-profile-service
    password: superSecret
    url: jdbc:mysql://localhost:3306/profile?serverTimezone=Europe/Berlin
  jpa:
    hibernate:
      ddl-auto: create
jpa:
  hibernate:
    ddl-auto: create
eureka:
  client:
    enabled: false
---
spring:
  profiles: localDev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: pwr-profile-service
    password: secretPassword
    url: jdbc:mysql://localhost:3306/profile
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
eureka:
  client:
    enabled: true
    service-url:
       defaultZone: http://localhost:8761/eureka
---
spring:
  profiles: localDevNoEureka
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: pwr-profile-service
      password: secretPassword
      url: jdbc:mysql://localhost:3306/profile
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
eureka:
  client:
    enabled: false
pwr-skill-service.ribbon.listOfServers: localhost:9003



